# Generated by Django 5.0.1 on 2024-02-25 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Предстоит', 'Предстоит'), ('Идёт', 'Идёт'), ('Завершен', 'Завершен'), ('Отменен', 'Отменен')], default='Предстоит', max_length=10, verbose_name='Статус события')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена')),
                ('total_seats', models.PositiveSmallIntegerField(default=0, verbose_name='Всего мест')),
                ('remaining_seats', models.PositiveIntegerField(default=0, verbose_name='Осталось мест')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Начало прогулки')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Конец прогулки')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория')),
                ('route', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalog.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Прогулка',
                'verbose_name_plural': 'Прогулки',
                'db_table': 'tblevents',
            },
        ),
        migrations.CreateModel(
            name='EventProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('schedule.event',),
        ),
    ]
