# Generated by Django 5.0.1 on 2024-02-22 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_category_image_alter_route_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Цена')),
                ('total_seats', models.PositiveSmallIntegerField(verbose_name='Всего мест')),
                ('remaining_seats', models.PositiveIntegerField(verbose_name='Осталось мест')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Начало прогулки')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Конец прогулки')),
                ('status', models.CharField(default='Предстоит', max_length=50, verbose_name='Статус события')),
                ('category', models.ForeignKey(default='SUP-прогулка', on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Прогулка',
                'verbose_name_plural': 'Прогулки',
                'db_table': 'tblevents',
            },
        ),
    ]
