# Generated by Django 5.0.1 on 2024-02-24 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_image_alter_route_image'),
        ('schedule', '0002_alter_event_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('schedule.event',),
        ),
        migrations.AlterField(
            model_name='event',
            name='route',
            field=models.ForeignKey(limit_choices_to={'category': models.ForeignKey(default='SUP-прогулка', on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Категория')}, on_delete=django.db.models.deletion.CASCADE, to='catalog.route', verbose_name='Маршрут'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Предстоит', 'Предстоит'), ('Идёт', 'Идёт'), ('Завершен', 'Завершен'), ('Отменен', 'Отменен')], default='Предстоит', max_length=10, verbose_name='Статус события'),
        ),
    ]
