# Generated by Django 5.0.1 on 2024-02-22 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorder',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.event', verbose_name='Прогулка'),
        ),
    ]
