# Generated by Django 5.0.1 on 2024-02-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseorder',
            old_name='name',
            new_name='fullname',
        ),
    ]
